name: "Build Test and Deploy API to EC2 instance"
run-name: "Build Test and Deploy API to EC2 instance"

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11 and cache it
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd api
        pip install -r requirements.txt
        cd ~
    - name: Test with unittest
      run: |
        cd api
        python -m unittest test
        cd ~
    - name: Deploy to EC2 through ssh
      env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          APP_DIR: ${{ secrets.APP_DIR }}

      run: |
        echo "$AWS_PRIVATE_KEY" > private_key && chmod 400 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ec2-user@${HOST_NAME} "
          cd ${APP_DIR} &&
          git pull &&
          kill -9 $(ps -a | grep "flask" | grep -v "grep" | awk '{print $1}') &&
          tmux attach -f API &&
          flask run --host=0.0.0.0 --port=8000 "
